apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../dev

nameSuffix: .${feature}

patches:
- target:
    kind: Composition
  patch: |-
    - op: replace
      path: /spec/compositeTypeRef/apiVersion
      value: database.example.org.${feature}/v1alpha1
    - op: replace
      path: /metadata/labels/crossplane.io~1xrd
      value: xpostgresqlinstances.database.example.org.${feature}
- target:
    kind: CompositeResourceDefinition
  patch: |-
    - op: replace
      path: /spec/group
      value: database.example.org.${feature}

commonLabels:
  feature: ${feature}
