# NOTE: Strategic merge patches like this one will not work, they will wipe out too many fields.
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  resources:
  - name: cloudsqlinstance
    base:
      spec:
        forProvider:
          settings:
            dataDiskType: PD_HDD
