apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesJson6902:
- target:
    version: v1
    kind: Composition
    name: example
  path: composition-patch.yaml

## NOTE: Strategic merge patches for Crossplane v1.9.0 CRDs not working.
#
#openapi:
#  path: openapi.yaml
#patches:
#- ./composition-patch.not-working.yaml


commonLabels:
  env: development
